- docs/team/cshuwen.md
> Add skeletal PPP file for CShuwen

- docs/team/cydtseng.md
> Add preliminary Project Portfolio Page for Chen-Yu

- docs/team/jiayan-lim.md
> Add Project Portfolio Page (PPP) Lim Jia Yan

- docs/team/nevinlim.md
> updated nevinlim.md for skeletal PPP

- README.md
- docs/_sass/minima/_base.scss
> updated README.md and _base.scss

- docs/DeveloperGuide.md
> Update use case and glossary for DP

- docs/UserGuide.md
> Complete user guide markdown

- docs/_config.yml
Made some changes to repo url and title for website
> updated _config.yml

- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/model/drug/Allergy.java
- src/main/java/seedu/address/model/drug/DrugName.java
- src/main/java/seedu/address/model/drug/ProductionDate.java
- src/main/java/seedu/address/model/drug/StorageCondition.java
Include flags for drug and patient
> Edit CliSyntax

- src/main/java/seedu/address/model/drug/ActiveIngredient.java
- src/main/java/seedu/address/model/drug/Direction.java
- src/main/java/seedu/address/model/drug/Drug.java
- src/main/java/seedu/address/model/drug/ExpiryDate.java
- src/main/java/seedu/address/model/drug/UniqueDrugList.java
Implemented ActiveIngredient, Direction, Drug, UniqueDrugList classes
> Implement Drug classes

- docs/team/nevinlim.md
- src/main/java/seedu/address/model/drug/ExpiryDate.java
- src/main/java/seedu/address/model/drug/Purpose.java
- src/main/java/seedu/address/model/drug/SideEffect.java
- src/main/java/seedu/address/model/drug/StorageCount.java
- src/main/java/seedu/address/model/drug/TradeName.java
Fixes #42
Implemented Drug classes: TradeName, StorageCount, ExpiryDate, SideEffect and Purpose
> updated DrugModel classes

- src/main/java/seedu/address/commons/util/StringUtil.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/person/patient/DateOfBirth.java
- src/main/java/seedu/address/model/person/patient/DrugAllergy.java
- src/main/java/seedu/address/model/person/patient/EmergencyContact.java
- src/main/java/seedu/address/model/person/patient/Gender.java
- src/main/java/seedu/address/model/person/patient/IC.java
- src/main/java/seedu/address/model/person/patient/Ic.java
- src/main/java/seedu/address/model/person/patient/Patient.java
- src/test/java/seedu/address/commons/util/StringUtilTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
- src/test/java/seedu/address/model/person/patient/DateOfBirthTest.java
- src/test/java/seedu/address/model/person/patient/DrugAllergyTest.java
- src/test/java/seedu/address/model/person/patient/EmergencyContactTest.java
- src/test/java/seedu/address/model/person/patient/GenderTest.java
- src/test/java/seedu/address/model/person/patient/IcTest.java
- src/test/java/seedu/address/model/person/patient/PatientTest.java
Fixes #48 
Implement all classes under the patient package.
Modified person class for backward comparability.
Add a new function in string util to achieve case-insensitive feature for user input.
Add test cases for functions that have been implemented.
> Update patient model partially 

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/drugcommands/AddCommand.java
- src/main/java/seedu/address/logic/commands/drugcommands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/drugcommands/FindCommand.java
- src/main/java/seedu/address/logic/commands/drugcommands/ListCommand.java
- src/main/java/seedu/address/logic/commands/generalcommand/ExitCommand.java
- src/main/java/seedu/address/logic/commands/generalcommand/HelpCommand.java
- src/main/java/seedu/address/logic/commands/patientcommands/AddCommand.java
- src/main/java/seedu/address/logic/commands/patientcommands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/patientcommands/FindCommand.java
- src/main/java/seedu/address/logic/commands/patientcommands/ListCommand.java
- src/main/java/seedu/address/logic/parser/CareFlowParser.java
- src/main/java/seedu/address/logic/parser/drugparser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/drugparser/DeleteCommandParser.java
- src/main/java/seedu/address/logic/parser/drugparser/DrugParser.java
- src/main/java/seedu/address/logic/parser/drugparser/FindCommandParser.java
- src/main/java/seedu/address/logic/parser/generalparser/GeneralParser.java
- src/main/java/seedu/address/logic/parser/patientparser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/patientparser/DeleteCommandParser.java
- src/main/java/seedu/address/logic/parser/patientparser/FindCommandParser.java
- src/main/java/seedu/address/logic/parser/patientparser/PatientParser.java
Updated Parser hierarchy such that the top level parser is now CareFlowParser, which distributes tasks to GeneralParser/PatientParser/ DrugParser. The 3 secondary parsers then switch to each specific command parsers.
> Update Parser hierarchy

- src/main/java/seedu/address/logic/commands/patientcommands/AddCommand.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/logic/parser/patientparser/AddCommandParser.java
- src/main/java/seedu/address/model/CareFlow.java
- src/main/java/seedu/address/model/PatientRecord.java
- src/main/java/seedu/address/model/person/exceptions/DuplicatePatientException.java
- src/main/java/seedu/address/model/person/exceptions/PatientNotFoundException.java
- src/main/java/seedu/address/model/person/patient/DateOfBirth.java
- src/main/java/seedu/address/model/person/patient/Ic.java
- src/main/java/seedu/address/model/person/patient/UniquePatientList.java
Fix #58 
- add command for patient
- add command parser for patient
- unique patient list
- duplicate patient exception
- patient not found exception
Program currently not able to run due to getPatientRecordFilePath in CareFlowModelManager returning null, pending implementation of userPrefs.getPatientRecordFilePath().
> Add Command For Patient

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/patientcommands/DeleteCommand.java
- src/main/java/seedu/address/logic/parser/patientparser/DeleteCommandParser.java
Implement DeleteCommand adn DeleteCommandParser Classes. Partially fixes #59
> add DeleteCommand to patient record system

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/drugcommands/AddCommand.java
- src/main/java/seedu/address/logic/commands/drugcommands/DeleteCommand.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/logic/parser/drugparser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/drugparser/DeleteCommandParser.java
- src/main/java/seedu/address/model/drug/TradeName.java
implemented delete command under drug command
implemented delete command parser under drug parser
partially implemented add command parser under drug parser (incomplete)
added some methods in parserUtil
partially fixes #44 
iterative implementation, not sure if there's a more optimal way to do it.
> Delete command for Drug

- src/main/java/seedu/address/logic/commands/patientcommands/AddCommand.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/logic/parser/patientparser/AddCommandParser.java
- src/main/java/seedu/address/model/person/patient/UniquePatientList.java
> Change parser to read only emergency contact number

- src/main/java/seedu/address/storage/JsonAdaptedDrug.java
> Add JsonAdaptedDrug class

- src/main/java/seedu/address/model/person/DateOfBirth.java
- src/main/java/seedu/address/model/person/Gender.java
- src/main/java/seedu/address/model/person/Ic.java
- src/main/java/seedu/address/ui/DrugCard.java
- src/main/java/seedu/address/ui/PatientDrugListPanel.java
- src/main/java/seedu/address/ui/PersonCard.java
Change PersonCard to PatientCard.
Add DrugCard.
Update PatientDrugListPanel
> Update UI for patient and drug

- src/main/java/seedu/address/model/UserPrefs.java
- src/main/java/seedu/address/model/drug/StorageCount.java
- src/main/java/seedu/address/storage/CareFlowStorage.java
- src/main/java/seedu/address/storage/CareFlowStorageManager.java
- src/main/java/seedu/address/storage/DrugInventoryStorage.java
- src/main/java/seedu/address/storage/JsonAddressBookStorage.java
- src/main/java/seedu/address/storage/JsonDrugInventoryStorage.java
- src/main/java/seedu/address/storage/JsonPatientRecordStorage.java
- src/main/java/seedu/address/storage/PatientRecordStorage.java
- src/main/java/seedu/address/storage/StorageManager.java
Created DrugInventoryStorage, PatientRecordStorage, CareFlowStorage, JsonDrugInventoryStorage, JsonPatientRecordStorage, CareFlowStorageManager classes for the storage of CareFlow data
> Add storage classes

- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/logic/CareFlowLogic.java
- src/main/java/seedu/address/logic/CareFlowLogicManager.java
- src/main/java/seedu/address/model/CareFlow.java
- src/main/java/seedu/address/model/CareFlowModel.java
- src/main/java/seedu/address/model/CareFlowModelManager.java
- src/main/java/seedu/address/ui/DrugCard.java
- src/main/java/seedu/address/ui/StatusBarFooter.java
removed the unused careflow constructors 
fixed some checkstyle errors
> Fixed some checkstyle errors

- src/main/java/seedu/address/ui/DrugListPanel.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/PatientListPanel.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/DrugListPanel.fxml
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/PatientListCard.fxml
- src/main/resources/view/PatientListPanel.fxml
fix #93 
- added tabpanes to separate drugs and patients
- minor updates to list cell layout and design
> Add tabpanes for separation

- src/main/java/seedu/address/commons/core/LogsCenter.java
addressbook.log -> careflow.log
> Update log file path

- preferences.json
- src/main/java/seedu/address/model/drug/ActiveIngredient.java
- src/main/java/seedu/address/model/drug/Direction.java
- src/main/java/seedu/address/model/drug/Purpose.java
- src/main/java/seedu/address/model/drug/SideEffect.java
- src/main/java/seedu/address/model/drug/StorageCount.java
- src/main/java/seedu/address/model/drug/TradeName.java
- src/main/java/seedu/address/model/person/Address.java
- src/main/java/seedu/address/model/person/DrugAllergy.java
- src/main/java/seedu/address/model/person/Name.java
- src/main/java/seedu/address/model/person/Phone.java
Implemented constraints for user input 
Fixes #89
> Constraints for all user input

- src/main/java/seedu/careflow/model/person/Phone.java
Set phone number to accept at least 3 digits instead of 8 digits.
> Change phone number restriction

- src/main/java/seedu/careflow/MainApp.java
- src/main/java/seedu/careflow/ui/HelpWindow.java
- src/main/resources/stylesheet/HelpWindow.css
- src/main/resources/stylesheet/HelpWindowLight.css
- src/main/resources/view/HelpWindow.fxml
Changed copyUrl  button in help window to openUrl button
> Implemented open URL button in help window

- src/main/java/seedu/careflow/model/person/Patient.java
- src/main/java/seedu/careflow/ui/DrugListPanel.java
- src/main/java/seedu/careflow/ui/MainWindow.java
- src/main/java/seedu/careflow/ui/PatientListPanel.java
> Allow concurrent patient/drug and patient/drug Detail Display

- docs/UserGuide.md
> change line for back to top link

- src/test/java/seedu/careflow/logic/parser/CommandParserTestUtil.java
- src/test/java/seedu/careflow/logic/parser/patientparser/AddCommandParserTest.java
- src/test/java/seedu/careflow/testutil/PatientBuilder.java
> Add junit tests for AddCommandParser

- src/test/java/seedu/careflow/logic/parser/patientparser/UpdateCommandParserTest.java
> Add JUnit tests for patient UpdateCommandParser

- src/main/java/seedu/careflow/logic/commands/drugcommands/DeleteCommand.java
- src/main/java/seedu/careflow/logic/commands/drugcommands/UpdateCommand.java
- src/main/java/seedu/careflow/logic/parser/CliSyntax.java
- src/main/java/seedu/careflow/logic/parser/drugparser/DeleteCommandParser.java
- src/main/java/seedu/careflow/logic/parser/drugparser/UpdateCommandParser.java
- src/main/java/seedu/careflow/model/drug/StorageCount.java
- src/test/java/seedu/careflow/logic/parser/drugparser/AddCommandParserTest.java
- src/test/java/seedu/careflow/logic/parser/drugparser/DeleteCommandParserTest.java
- src/test/java/seedu/careflow/logic/parser/drugparser/FindCommandParserTest.java
- src/test/java/seedu/careflow/logic/parser/drugparser/UpdateCommandParserTest.java
- src/test/java/seedu/careflow/testutil/DrugBuilder.java
implemented AddCommandParserTest, DeleteCommandParserTest, FindCommandParserTest, UpdateCommandParserTest for Drug
changed the Drug update value prefix from -up to -val which is more relevant
Fixes #147 , #148 , #149 , #150
> implemented JUnitTests for DrugCommandParsers

- build.gradle
> Enable assertions for tp by modifying build.gradle

- docs/DeveloperGuide.md
> Update value proposition for DG

- docs/diagrams/UiClassDiagram.puml
- src/main/java/seedu/careflow/logic/commands/drugcommands/AddCommand.java
- src/main/java/seedu/careflow/logic/commands/drugcommands/DeleteCommand.java
- src/main/java/seedu/careflow/logic/commands/drugcommands/FindCommand.java
- src/main/java/seedu/careflow/logic/commands/drugcommands/UpdateCommand.java
- src/main/java/seedu/careflow/logic/commands/patientcommands/AddCommand.java
- src/main/java/seedu/careflow/logic/commands/patientcommands/DeleteCommand.java
- src/main/java/seedu/careflow/logic/commands/patientcommands/FindCommand.java
- src/main/java/seedu/careflow/logic/commands/patientcommands/UpdateCommand.java
- src/main/java/seedu/careflow/ui/DrugPieChartPanel.java
partially fixes #161
update Ui class diagram in DG.
> update UML diagrams in Developer Guide

- docs/UserGuide.md
- src/main/java/seedu/careflow/logic/parser/CareFlowParser.java
- src/main/java/seedu/careflow/ui/MainWindow.java
- src/test/java/seedu/careflow/logic/CareFlowLogicManagerTest.java
> update User Guide by adding view command

- src/main/java/seedu/careflow/ui/PatientListPanel.java
- src/main/java/seedu/careflow/ui/ResultDisplay.java
- src/main/resources/stylesheet/DarkTheme.css
> set wrap test for the result display textarea

- src/main/java/seedu/careflow/ui/DrugListPanel.java
- src/main/java/seedu/careflow/ui/MainWindow.java
- src/main/resources/stylesheet/DarkTheme.css
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/ResultDisplay.fxml
> Branch add careflow bot img

- docs/UserGuide.md
- src/main/java/seedu/careflow/logic/commands/drugcommands/ViewCommand.java
- src/main/java/seedu/careflow/logic/parser/drugparser/ViewCommandParser.java
- src/main/java/seedu/careflow/logic/parser/patientparser/ViewCommandParser.java
- src/main/java/seedu/careflow/ui/DrugListPanel.java
- src/main/java/seedu/careflow/ui/PatientListPanel.java
correct bugs in patient and drug display upon deletion of patient/drug, correct the mistakes in view feedback, fixes #256, #234, #238,
>  bug fixing in patient/drug display

- src/main/java/seedu/careflow/model/patient/DateOfBirth.java
- src/test/java/seedu/careflow/logic/parser/patientparser/UpdateCommandParserTest.java
- src/test/java/seedu/careflow/model/patient/DateOfBirthTest.java
Validate date for the edge case
- detect invalid date like 29/2/2003, 31/4/2000
- allow user to input boundary date(i.e.: 01/01/1990, today) as date of birth
Fix #231 
Fix #245 
Fix #254
> Fix bug in dob

- src/main/java/seedu/careflow/model/CareFlowModelManager.java
- src/main/java/seedu/careflow/model/patient/Phone.java
- src/main/java/seedu/careflow/storage/JsonAdaptedPatient.java
- src/test/java/seedu/careflow/logic/commands/patientcommands/PatientCommandTestUtil.java
- src/test/java/seedu/careflow/logic/parser/patientparser/AddCommandParserTest.java
- src/test/java/seedu/careflow/logic/parser/patientparser/UpdateCommandParserTest.java
- src/test/java/seedu/careflow/model/patient/PhoneTest.java
- src/test/java/seedu/careflow/testutil/HospitalBuilder.java
- src/test/java/seedu/careflow/testutil/TypicalHospitals.java
Fix the issue in JSonAdaptedPatient that affects `update` command when the user updates with the drug allergy field.
- consider functionality bug coz this cause all patient command that include with drug allergy field not working correctly(due to copy and paste issue in 'JSonAdaptedPatient' class)
Fix #260
> Fix bug in storage

- docs/UserGuide.md
- src/main/java/seedu/careflow/logic/parser/drugparser/UpdateCommandParser.java
- src/main/java/seedu/careflow/model/drug/StorageCount.java
- src/test/java/seedu/careflow/logic/parser/drugparser/AddCommandParserTest.java
Fixes #259 
Fixes #253 
Fixes #248 
Fixes #227 
Fixes #237
> Bug fixes 

- docs/UserGuide.md
- src/main/java/seedu/careflow/logic/commands/drugcommands/ViewCommand.java
- src/main/java/seedu/careflow/ui/DrugPieChartPanel.java
fix #261 
fix #229 
fix #251 
fix #249
> Fix PE-D issues: 0 drug count, spelling errors and user guide formatting

- preferences.json
> Change path separator to ensure consistent ui display

- docs/UserGuide.md
> Branch ped fixes

- docs/DeveloperGuide.md
Include feature flaw suggested by the tester in PE-D in the Enhancement section in DG.
> Add enhancement section in dg appendix

- docs/UserGuide.md
> restructure ug numbering to include data storage section

- src/main/java/seedu/careflow/model/patient/DateOfBirth.java
- src/test/java/seedu/careflow/model/patient/DateOfBirthTest.java
- check for boundary date, ie 01/01/1900
> Fix bug for dob

- src/main/java/seedu/careflow/logic/commands/CommandResult.java
- src/main/java/seedu/careflow/logic/commands/drugcommands/UpdateCommand.java
- src/main/java/seedu/careflow/logic/commands/drugcommands/ViewCommand.java
- src/main/java/seedu/careflow/logic/commands/patientcommands/UpdateCommand.java
- src/main/java/seedu/careflow/logic/commands/patientcommands/ViewCommand.java
- src/main/java/seedu/careflow/ui/DrugListPanel.java
- src/main/java/seedu/careflow/ui/MainWindow.java
- src/main/java/seedu/careflow/ui/PatientListPanel.java
> correct feedback in view command

- docs/UserGuide.md
> Add windows terminal instructions for UG.

- docs/UserGuide.md
- docs/diagrams/DrugFindCommandSequenceDiagram.puml
- docs/team/nevinlim.md
- Added table for drug parameters in UG
- Minor adjustments for DrugFindCommandSequenceDiagram.puml
> UGDG update
